/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.*;


public class Form extends javax.swing.JFrame {
    
        private final String url = "jdbc:sqlserver://localhost\\ADSW;databaseName=CoursesPlatformDB;"
                             + "user=sa;password=2004;"
                             + "encrypt=true;trustServerCertificate=true;";
    

    
     
    public Form() {
        initComponents();
         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Cannot Load JDBC Driver !!!");
 }       
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        radioStudent = new javax.swing.JRadioButton();
        radioInstructor = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPassword2 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        radioStudent2 = new javax.swing.JRadioButton();
        radioInstructor2 = new javax.swing.JRadioButton();
        btnRegister = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtIDs = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtNewPassword = new javax.swing.JPasswordField();
        txtOldPassword = new javax.swing.JPasswordField();
        radiostudentup = new javax.swing.JRadioButton();
        radioinstructorsup = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 110, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 110, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Welcome to learning platform");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 370, 46));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Vektoren _ Kostenloser Download.jpeg"))); // NOI18N
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 470));

        jTabbedPane1.addTab("Home", jPanel5);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Username :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 110, 30));

        txtUsername.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 200, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Password :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 110, 29));

        txtPassword.setBackground(new java.awt.Color(204, 204, 204));
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPasswordMouseEntered(evt);
            }
        });
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 200, 30));

        btnLogin.setBackground(new java.awt.Color(204, 204, 204));
        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 100, 35));

        buttonGroup1.add(radioStudent);
        radioStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        radioStudent.setText("Student");
        jPanel2.add(radioStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 120, -1));

        buttonGroup1.add(radioInstructor);
        radioInstructor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        radioInstructor.setText("Instructor");
        jPanel2.add(radioInstructor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 120, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/6e51d9d9-c275-486b-8cc8-d07557ec1fcf.jpeg"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 510, 470));

        jTabbedPane1.addTab("Login", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Username :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, 30));

        txtUsername2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.add(txtUsername2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 200, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Password :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 130, 30));

        txtPassword2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.add(txtPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 200, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Full Name :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, 30));

        txtFullName.setBackground(new java.awt.Color(204, 204, 204));
        txtFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFullNameActionPerformed(evt);
            }
        });
        jPanel3.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 200, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Confirm Password :");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 180, 30));

        txtConfirmPassword.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.add(txtConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 200, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Email :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 130, 30));

        txtEmail.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 200, 30));

        buttonGroup2.add(radioStudent2);
        radioStudent2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        radioStudent2.setText("Student");
        jPanel3.add(radioStudent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 98, -1));

        buttonGroup2.add(radioInstructor2);
        radioInstructor2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        radioInstructor2.setText("Instructor");
        radioInstructor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioInstructor2ActionPerformed(evt);
            }
        });
        jPanel3.add(radioInstructor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 120, -1));

        btnRegister.setBackground(new java.awt.Color(204, 204, 204));
        btnRegister.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 100, 35));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("ID :");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 43, -1));

        txtIDs.setBackground(new java.awt.Color(204, 204, 204));
        txtIDs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDsActionPerformed(evt);
            }
        });
        jPanel3.add(txtIDs, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 200, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/6e51d9d9-c275-486b-8cc8-d07557ec1fcf.jpeg"))); // NOI18N
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 470));

        jTabbedPane1.addTab("Register", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText(" New password :");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(204, 204, 204));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel4.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Old pasword :");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));
        jPanel4.add(txtNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 239, -1));
        jPanel4.add(txtOldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 239, -1));

        buttonGroup4.add(radiostudentup);
        radiostudentup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        radiostudentup.setText("Student");
        radiostudentup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiostudentupActionPerformed(evt);
            }
        });
        jPanel4.add(radiostudentup, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 190, -1));

        buttonGroup4.add(radioinstructorsup);
        radioinstructorsup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        radioinstructorsup.setText("Instructor");
        radioinstructorsup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioinstructorsupActionPerformed(evt);
            }
        });
        jPanel4.add(radioinstructorsup, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/6e51d9d9-c275-486b-8cc8-d07557ec1fcf.jpeg"))); // NOI18N
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 470));

        jTabbedPane1.addTab("Update", jPanel4);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Adv. Software Engineering");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("learning platform project");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 321, 34));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Mohamed hassany elabd");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Jonathan atef mores");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Mohamed ahmed essa");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Mohamed abdelbasset mohamed");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Mahmoud ahmed Mahmoud");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Mohamed reda mohamed kilany");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 240, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Vektoren _ Kostenloser Download.jpeg"))); // NOI18N
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 470));

        jTabbedPane1.addTab("About us", jPanel6);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/learning platform course.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 1093, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Courses", jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordMouseEntered

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username = txtUsername.getText();
String password = new String(txtPassword.getPassword());

String role = "";
if (radioStudent.isSelected()) {
    role = "Student";
} else if (radioInstructor.isSelected()) {
    role = "Instructor";
} else {
    JOptionPane.showMessageDialog(null, "Please select a role (Student or Instructor)");
    return;
}

try (Connection conn = DriverManager.getConnection(url)) {
    String sql;
    if (role.equals("Student")) {
        sql = "SELECT StudentID, FullName, Email FROM Students WHERE user_name = ? AND Password = ?";
    } else {
        sql = "SELECT InstructorID,FullName , Email FROM Instructors WHERE user_name = ? AND Password = ?";
    }

    PreparedStatement ps = conn.prepareStatement(sql);
    ps.setString(1, username);
    ps.setString(2, password);
    
    ResultSet rs = ps.executeQuery();

    if (rs.next()) {
        String fullName = rs.getString("FullName");
        String email = rs.getString("Email");
        JOptionPane.showMessageDialog(null, "Login successful as " + role + 
                                    "\nName: " + fullName + 
                                    "\nEmail: " + email);
    } else {
        JOptionPane.showMessageDialog(null, "Invalid username, password, or role.");
    }

} catch (Exception ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(null, "Database error: " + ex.getMessage());
}
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        String fullName = txtFullName.getText();
String username = txtUsername2.getText();
String password = new String(txtPassword2.getPassword());
String confirmPassword = new String(txtConfirmPassword.getPassword());
String email = txtEmail.getText();
String IDs = txtIDs.getText();

String role = "";
if (radioStudent2.isSelected()) {
    role = "Student";
} else if (radioInstructor2.isSelected()) {
    role = "Instructor";
} else {
    JOptionPane.showMessageDialog(null, "Please select a role.");
    return;
}

// التحقق من البيانات
if (fullName.isEmpty() || username.isEmpty() || password.isEmpty() || confirmPassword.isEmpty() || email.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Please fill all fields.");
    return;
}

if (!password.equals(confirmPassword)) {
    JOptionPane.showMessageDialog(null, "Passwords do not match.");
    return;
}

try (Connection conn = DriverManager.getConnection(url)) {
    // التحقق من وجود اسم المستخدم مسبقاً
    String checkSql;
    if (role.equals("Student")) {
        checkSql = "SELECT * FROM Students WHERE user_name = ?";
    } else {
        checkSql = "SELECT * FROM Instructors WHERE user_name = ?";
    }
    
    PreparedStatement checkStmt = conn.prepareStatement(checkSql);
    checkStmt.setString(1, username);
    ResultSet rs = checkStmt.executeQuery();

    if (rs.next()) {
        JOptionPane.showMessageDialog(null, "Username already exists.");
        return;
    }

    // إضافة المستخدم الجديد
    String insertSql;
    if (role.equals("Student")) {
        insertSql = "INSERT INTO Students (StudentID,FullName, Email, user_name, Password) VALUES ( ?,?, ?, ?, ?)";
    } else {
        insertSql = "INSERT INTO Instructors (InstructorID,FullName, Email, user_name, Password) VALUES ( ?,?, ?, ?, ?)";
    }
    
    PreparedStatement insertStmt = conn.prepareStatement(insertSql);
    insertStmt.setString(1, IDs);
    insertStmt.setString(2, fullName);
    insertStmt.setString(3, email);
    insertStmt.setString(4, username);
    insertStmt.setString(5, password);
    

    

    int rowsInserted = insertStmt.executeUpdate();

    if (rowsInserted > 0) {
        JOptionPane.showMessageDialog(null, "Registration successful as " + role + "!");
    } else {
        JOptionPane.showMessageDialog(null, "Registration failed. Try again.");
    }

} catch (Exception ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(null, "Database error: " + ex.getMessage());
}
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void radioInstructor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioInstructor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioInstructor2ActionPerformed

    private void txtIDsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDsActionPerformed

    private void txtFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFullNameActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here: 
        String oldPassword = new String(txtOldPassword.getPassword());
    String newPassword = new String(txtNewPassword.getPassword());
    
    // 2. تحديد نوع المستخدم من RadioButton
    String role = "";
    if (radiostudentup.isSelected()) {
        role = "Student";
    } else if (radioinstructorsup.isSelected()) {
        role = "Instructor";
    } else {
        JOptionPane.showMessageDialog(this, "Please select your role (Student or Instructor)");
        return;
    }

    // 3. التحقق الأساسي من الحقول
    if (oldPassword.isEmpty() || newPassword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "يجب إدخال كلمة المرور القديمة والجديدة");
        return;
    }

    try (Connection conn = DriverManager.getConnection(url)) {
        // 4. إنشاء استعلام التحديث
        String tableName = role.equals("Student") ? "Students" : "Instructors";
        String sql = "UPDATE " + tableName + " SET Password = ? WHERE Password = ?";
        
        // 5. تنفيذ الاستعلام
        try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, newPassword); // كلمة المرور الجديدة
            pstmt.setString(2, oldPassword); // كلمة المرور القديمة
            
            int rowsUpdated = pstmt.executeUpdate();
            
            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this, "تم تحديث كلمة المرور بنجاح");
                txtOldPassword.setText("");
                txtNewPassword.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "كلمة المرور القديمة غير صحيحة");
            }
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "خطأ في قاعدة البيانات: " + ex.getMessage());
        ex.printStackTrace();
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void radiostudentupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiostudentupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiostudentupActionPerformed

    private void radioinstructorsupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioinstructorsupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioinstructorsupActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTabbedPane1.setSelectedComponent(jPanel2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTabbedPane1.addTab("Register", jPanel3);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton radioInstructor;
    private javax.swing.JRadioButton radioInstructor2;
    private javax.swing.JRadioButton radioStudent;
    private javax.swing.JRadioButton radioStudent2;
    private javax.swing.JRadioButton radioinstructorsup;
    private javax.swing.JRadioButton radiostudentup;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtIDs;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JPasswordField txtOldPassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPassword2;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtUsername2;
    // End of variables declaration//GEN-END:variables
}
